### ISSUE TITLE
example input file is missing?

### ISSUE THREAD

**Issue by PaulGeoerg** [PedestrianDynamics/EXIT89#1]
The description refers to an input file called `UOFUNGT3.DAT`, which is unfortunately missing.

**Comment by chraibi** [comment]
Hi Paul,
it's the same file as DPHILTMP.DAT under data. TO avoid confusion, I updated the README.

**Comment by PaulGeoerg** [comment]
Hi Mohcine, 
that's what I suspected! Thanks for the clarification and for editing the README.
